version: "3.3"
services:
  mysql:
    container_name: "admin_mysql"
    image: mysql:8.0.26
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=parkar
      - MYSQL_USER=user
      - MYSQL_PASSWORD=parkarparkar
  admin_service:
    container_name: "admin_service"
    image: nicerwang/parkar-admin:latest