version: "3.3"
services:
  mysql:
    container_name: "management_mysql"
    image: mysql:8.0.26
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./sql:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=parkar
      - MYSQL_USER=user
      - MYSQL_PASSWORD=parkarparkar
    ports:
      - "3306:3306"
  management_service:
    container_name: "management_service"
    image: nicerwang/parkar-management:latest
    ports:
      - "8080:8080"