name: deploy-adapter

on:
  push:
    tags:
      - 'va*'

jobs:
  adapter:
    runs-on: ubuntu-latest
    steps:
      - name: Docker - Fetch metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nicerwang/parkar-adapter
      - uses: actions/checkout@v2
      - name: JAVA - Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Maven - Build
        run: cd adapter && mvn package -Dmaven.test.skip=true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker - Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker - Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./adapter/
          file: ./adapter/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Deploy bash
        uses: fifsky/ssh-action@master
        with:
          command: |
            sh start-adapter.sh
          host: ${{ secrets.HOST_USER }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}