name: deploy-frontend-management

on:
  push:
    tags:
      - 'vfm*'

jobs:
  frontend-management:
    runs-on: ubuntu-latest
    steps:
      - name: Docker - Fetch metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nicerwang/parkar-frontend-management
      - uses: actions/checkout@v2
      - name: Node.js - Set up
        uses: actions/setup-node@v2.4.1
      - name: NPM - Build
        run: cd frontend-management &&  npm install --registry=https://registry.npm.taobao.org && npm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker - Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker - Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend-management/
          file: ./frontend-management/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Deploy bash
        uses: fifsky/ssh-action@master
        with:
          command: |
            sh start-frontend-management.sh
          host: ${{ secrets.HOST_FRONT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}